// Product data with enhanced details and custom images
export const products = [
  {
    id: 1,
    name: "SOLARA Quantum Watch",
    description: "A timepiece that combines classic elegance with cutting-edge smart technology.",
    fullDescription:
      "The SOLARA Quantum Watch redefines luxury wearables with its perfect fusion of timeless design and advanced technology. Crafted from premium materials including titanium and sapphire crystal, this exceptional timepiece features a revolutionary holographic display that seamlessly transitions between classic analog and smart functionalities.",
    price: "$1,299",
    priceValue: 1299,
    category: "wearables",
    image: "https://images.unsplash.com/photo-1524805444758-089113d48a6d?q=80&w=2338&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1524805444758-089113d48a6d?q=80&w=2338&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1622434641406-a158123450f9?q=80&w=2304&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1548171915-e79a1fe12e5a?q=80&w=2187&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1617714651073-17a0fcd14f9e?q=80&w=2187&auto=format&fit=crop",
    ],
    new: true,
    rating: 5,
    reviewCount: 124,
    features: [
      "Holographic display with seamless transition between analog and digital",
      "Premium titanium case with sapphire crystal",
      "7-day battery life with wireless charging",
      "Advanced health monitoring including ECG and blood oxygen",
      "Water resistant to 100 meters",
      "Customizable watch faces with AI-powered personalization",
    ],
    colors: [
      { name: "Midnight Black", value: "#000000" },
      { name: "Silver Titanium", value: "#C0C0C0" },
      { name: "Rose Gold", value: "#B76E79" },
    ],
    specifications: [
      { name: "Case Material", value: "Grade 5 Titanium" },
      { name: "Display", value: '1.4" Holographic AMOLED' },
      { name: "Resolution", value: "454 x 454 pixels" },
      { name: "Processor", value: "SOLARA S1 Dual-Core" },
      { name: "Memory", value: "2GB RAM, 32GB Storage" },
      { name: "Battery", value: "410mAh Li-ion" },
      { name: "Battery Life", value: "Up to 7 days" },
      { name: "Water Resistance", value: "10 ATM (100m)" },
      { name: "Connectivity", value: "Bluetooth 5.2, Wi-Fi, NFC" },
      { name: "Sensors", value: "Heart rate, ECG, SpO2, Accelerometer, Gyroscope, Altimeter" },
      { name: "Dimensions", value: "44mm x 12.3mm" },
      { name: "Weight", value: "48g" },
    ],
  },
  {
    id: 2,
    name: "SOLARA Aura Speakers",
    description: "Immersive sound experience with ambient lighting that responds to your music.",
    fullDescription:
      "SOLARA Aura Speakers deliver an unparalleled audio experience that transcends ordinary sound systems. These architectural masterpieces combine premium acoustics with responsive ambient lighting that synchronizes with your music, creating a multi-sensory experience that transforms any space into an immersive environment of sound and light.",
    price: "$2,499",
    priceValue: 2499,
    category: "audio",
    image: "https://images.unsplash.com/photo-1545454675-3531b543be5d?q=80&w=2070&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1545454675-3531b543be5d?q=80&w=2070&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?q=80&w=2069&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1610123598195-eea6b6be4c48?q=80&w=2187&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1546435770-a3e426bf472b?q=80&w=2065&auto=format&fit=crop",
    ],
    new: false,
    rating: 4,
    reviewCount: 89,
    features: [
      "360° Spatial Audio with room-adapting technology",
      "Responsive ambient lighting with 16 million colors",
      "Hand-crafted premium materials with glass and aluminum construction",
      "Wireless connectivity with multi-room synchronization",
      "Voice control with AI assistant integration",
      "Custom sound profiles with automatic room calibration",
    ],
    colors: [
      { name: "Obsidian Black", value: "#0A0A0A" },
      { name: "Arctic White", value: "#F5F5F5" },
      { name: "Brushed Gold", value: "#D4AF37" },
    ],
    specifications: [
      { name: "Speaker Type", value: "360° Spatial Audio" },
      { name: "Drivers", value: "6 custom-designed drivers" },
      { name: "Frequency Response", value: "20Hz - 40kHz" },
      { name: "Amplifier", value: "Class D, 250W" },
      { name: "Connectivity", value: "Wi-Fi 6, Bluetooth 5.2, HDMI eARC, Optical" },
      { name: "Lighting", value: "Adaptive LED array with 16M colors" },
      { name: "Voice Control", value: "Built-in far-field microphones" },
      { name: "Dimensions", value: "300mm x 300mm x 450mm" },
      { name: "Weight", value: "7.2kg" },
      { name: "Power", value: "100-240V AC" },
      { name: "Wireless Range", value: "Up to 30m" },
      { name: "Multi-room Support", value: "Up to 12 speakers" },
    ],
  },
  {
    id: 3,
    name: "SOLARA Lumina Phone",
    description: "The ultimate luxury smartphone with a revolutionary holographic display.",
    fullDescription:
      "The SOLARA Lumina Phone represents the pinnacle of mobile luxury technology. Featuring our revolutionary holographic display that projects content above the screen for truly immersive viewing, this exceptional smartphone is crafted from rare materials including ceramic, titanium, and lab-grown sapphire crystal. Experience unparalleled performance, security, and exclusivity.",
    price: "$3,999",
    priceValue: 3999,
    category: "accessories",
    image: "https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?q=80&w=2329&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?q=80&w=2329&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1580910051074-3eb694886505?q=80&w=2065&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1565849904461-04a58ad377e0?q=80&w=2036&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1598327105666-5b89351aff97?q=80&w=2027&auto=format&fit=crop",
    ],
    new: true,
    rating: 5,
    reviewCount: 56,
    features: [
      "Revolutionary holographic display technology",
      "Aerospace-grade titanium frame with ceramic back",
      "Lab-grown sapphire crystal screen",
      "Advanced AI photography system with 8K video",
      "Quantum-secure encryption for ultimate privacy",
      "Exclusive concierge service included for 3 years",
    ],
    colors: [
      { name: "Phantom Black", value: "#0F0F0F" },
      { name: "Celestial Blue", value: "#1A237E" },
      { name: "Champagne Gold", value: "#F7E7CE" },
    ],
    specifications: [
      { name: "Display", value: '6.8" Holographic AMOLED' },
      { name: "Resolution", value: "3200 x 1440 pixels" },
      { name: "Processor", value: "SOLARA X1 Quantum" },
      { name: "RAM", value: "16GB LPDDR5" },
      { name: "Storage", value: "512GB / 1TB" },
      { name: "Battery", value: "5000mAh with 100W charging" },
      { name: "Main Camera", value: "108MP + 48MP + 48MP + ToF" },
      { name: "Front Camera", value: "32MP + 3D depth sensor" },
      { name: "Biometrics", value: "In-display fingerprint, 3D face recognition" },
      { name: "OS", value: "SOLARA OS (Android-based)" },
      { name: "Connectivity", value: "5G, Wi-Fi 6E, Bluetooth 5.3, NFC" },
      { name: "Dimensions", value: "162.3 x 74.6 x 8.2 mm" },
      { name: "Weight", value: "198g" },
    ],
  },
  {
    id: 4,
    name: "SOLARA Nebula Headphones",
    description: "Noise-cancelling headphones with premium materials and exceptional sound quality.",
    fullDescription:
      "SOLARA Nebula Headphones deliver an uncompromising audio experience wrapped in luxurious comfort. Handcrafted with the finest materials including memory foam cushions wrapped in genuine leather, these exceptional headphones feature our proprietary active noise cancellation technology that creates a perfect sanctuary of sound wherever you go.",
    price: "$899",
    priceValue: 899,
    category: "audio",
    image: "https://images.unsplash.com/photo-1599669454699-248893623440?q=80&w=2070&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1599669454699-248893623440?q=80&w=2070&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?q=80&w=2079&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?q=80&w=2088&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1546435770-a3e426bf472b?q=80&w=2065&auto=format&fit=crop",
    ],
    new: false,
    rating: 5,
    reviewCount: 112,
    features: [
      "Adaptive noise cancellation with environmental awareness mode",
      "Premium materials including Italian leather and anodized aluminum",
      "Custom-designed 45mm beryllium drivers",
      "Up to 30 hours battery life with wireless charging",
      "Spatial audio with head tracking",
      "Intuitive touch controls with haptic feedback",
    ],
    colors: [
      { name: "Onyx Black", value: "#0A0A0A" },
      { name: "Ivory White", value: "#FFFFF0" },
      { name: "Burgundy", value: "#800020" },
    ],
    specifications: [
      { name: "Driver Size", value: "45mm Beryllium" },
      { name: "Frequency Response", value: "4Hz - 40kHz" },
      { name: "Impedance", value: "32 ohms" },
      { name: "Noise Cancellation", value: "Adaptive ANC with 3 modes" },
      { name: "Battery Life", value: "30 hours (ANC on)" },
      { name: "Charging", value: "USB-C and Wireless Qi" },
      { name: "Connectivity", value: "Bluetooth 5.2, 3.5mm jack" },
      { name: "Codecs", value: "LDAC, aptX HD, AAC, SBC" },
      { name: "Weight", value: "320g" },
      { name: "Microphones", value: "8 beamforming mics" },
      { name: "Controls", value: "Touch panels with haptic feedback" },
      { name: "Water Resistance", value: "IPX4" },
    ],
  },
  {
    id: 5,
    name: "SOLARA Zenith Smart Home Hub",
    description: "Control your entire home with this elegant and powerful smart home system.",
    fullDescription:
      "The SOLARA Zenith Smart Home Hub transforms your living space into an intelligent environment that anticipates your needs and responds to your preferences. This elegantly designed hub serves as the command center for your entire smart home ecosystem, with intuitive controls, voice recognition, and AI-powered automation that learns and adapts to your lifestyle.",
    price: "$1,999",
    priceValue: 1999,
    category: "smart-home",
    image: "https://images.unsplash.com/photo-1558002038-1055907df827?q=80&w=2070&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1558002038-1055907df827?q=80&w=2070&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1557438159-51eec7a6c9e8?q=80&w=2070&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1544256718-3bcf237f3974?q=80&w=2071&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1585399000684-d2f72660f092?q=80&w=2071&auto=format&fit=crop",
    ],
    new: false,
    rating: 4,
    reviewCount: 78,
    features: [
      "Centralized control for all smart home devices",
      "AI-powered automation that learns your preferences",
      "Elegant design with floating display and ambient lighting",
      "Advanced security features with facial recognition",
      "Voice control with natural language processing",
      "Energy management system with usage analytics",
    ],
    colors: [
      { name: "Matte Black", value: "#121212" },
      { name: "Silver", value: "#C0C0C0" },
      { name: "Champagne", value: "#F7E7CE" },
    ],
    specifications: [
      { name: "Processor", value: "SOLARA H2 Octa-core" },
      { name: "Memory", value: "8GB RAM, 128GB Storage" },
      { name: "Display", value: '7" Floating Holographic' },
      { name: "Connectivity", value: "Wi-Fi 6, Bluetooth 5.2, Zigbee, Z-Wave, Thread" },
      { name: "Voice Recognition", value: "Far-field array with 6 microphones" },
      { name: "Compatibility", value: "Works with 10,000+ devices" },
      { name: "Security", value: "End-to-end encryption, biometric authentication" },
      { name: "Power", value: "AC adapter with battery backup" },
      { name: "Dimensions", value: "180mm x 180mm x 35mm" },
      { name: "Weight", value: "950g" },
      { name: "OS", value: "SOLARA Home OS" },
      { name: "Updates", value: "Automatic OTA updates" },
    ],
  },
  {
    id: 6,
    name: "SOLARA Eclipse Tablet",
    description: "Ultra-thin tablet with a stunning display and powerful performance.",
    fullDescription:
      "The SOLARA Eclipse Tablet redefines mobile computing with its impossibly thin profile and edge-to-edge display that brings content to life with unprecedented clarity and color accuracy. Crafted from a single piece of aerospace-grade aluminum with a diamond-cut edge, this premium tablet combines exceptional performance with sophisticated design for those who demand the extraordinary.",
    price: "$2,199",
    priceValue: 2199,
    category: "accessories",
    image: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?q=80&w=2033&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?q=80&w=2033&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1561154464-82e9adf32764?q=80&w=2187&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1623126908029-58cb08a2b272?q=80&w=2070&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1585790050230-5ab129de5f9c?q=80&w=2070&auto=format&fit=crop",
    ],
    new: false,
    rating: 5,
    reviewCount: 94,
    features: [
      "Ultra-thin 5.5mm aerospace-grade aluminum body",
      '12.9" Quantum Dot OLED display with 120Hz refresh rate',
      "SOLARA T1 processor with dedicated neural engine",
      "Advanced stylus with 4096 pressure levels and haptic feedback",
      "Quad speaker system tuned by acoustic engineers",
      "All-day battery life with fast charging",
    ],
    colors: [
      { name: "Space Gray", value: "#343d46" },
      { name: "Silver", value: "#e9e9e9" },
      { name: "Gold", value: "#e6c8a0" },
    ],
    specifications: [
      { name: "Display", value: '12.9" Quantum Dot OLED' },
      { name: "Resolution", value: "3000 x 2000 pixels" },
      { name: "Processor", value: "SOLARA T1 Octa-core" },
      { name: "RAM", value: "12GB LPDDR5" },
      { name: "Storage", value: "256GB / 512GB / 1TB" },
      { name: "Battery", value: "10,000mAh" },
      { name: "Cameras", value: "13MP rear, 8MP front with Center Stage" },
      { name: "Audio", value: "Quad speakers, triple microphones" },
      { name: "Connectivity", value: "Wi-Fi 6E, Bluetooth 5.2, 5G (optional)" },
      { name: "Ports", value: "USB-C Thunderbolt 4" },
      { name: "Dimensions", value: "280.6 x 214.9 x 5.5mm" },
      { name: "Weight", value: "560g" },
    ],
  },
  {
    id: 7,
    name: "SOLARA Celestial Lighting System",
    description: "Smart lighting that adapts to your mood and enhances your living space.",
    fullDescription:
      "The SOLARA Celestial Lighting System transforms your environment through the perfect harmony of light and technology. This comprehensive lighting solution features modular panels that can be arranged in countless configurations, creating dynamic light sculptures that respond to your mood, music, and daily routines. Experience lighting as an art form that enhances wellbeing and elevates your space.",
    price: "$1,499",
    priceValue: 1499,
    category: "smart-home",
    image: "https://images.unsplash.com/photo-1565814329452-e1efa11c5b89?q=80&w=2070&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1565814329452-e1efa11c5b89?q=80&w=2070&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?q=80&w=2070&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1540932239986-30128078f3c5?q=80&w=2187&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1611464908623-07f19927264e?q=80&w=2070&auto=format&fit=crop",
    ],
    new: true,
    rating: 5,
    reviewCount: 67,
    features: [
      "Modular design with customizable configurations",
      "16 million colors with dynamic lighting effects",
      "Circadian rhythm support for improved wellbeing",
      "Music synchronization with beat detection",
      "Voice and app control with scene presets",
      "Energy efficient with 50,000+ hour lifespan",
    ],
    colors: [
      { name: "White", value: "#FFFFFF" },
      { name: "Black", value: "#000000" },
      { name: "Brushed Aluminum", value: "#D3D3D3" },
    ],
    specifications: [
      { name: "Panel Type", value: "Modular LED panels" },
      { name: "Colors", value: "16 million colors (RGB+CCT)" },
      { name: "Brightness", value: "1200 lumens per panel" },
      { name: "Connectivity", value: "Wi-Fi, Bluetooth Mesh" },
      { name: "Control", value: "App, voice, touch, motion" },
      { name: "Power", value: "100-240V AC, 12W per panel" },
      { name: "Panel Dimensions", value: "150mm x 150mm x 10mm" },
      { name: "Expandability", value: "Up to 30 panels per controller" },
      { name: "Lifespan", value: "50,000+ hours" },
      { name: "Mounting", value: "3M adhesive or screw mount" },
      { name: "Effects", value: "40+ dynamic lighting scenes" },
      { name: "Integration", value: "Works with all major smart home systems" },
    ],
  },
  {
    id: 8,
    name: "SOLARA Orbit Earbuds",
    description: "Wireless earbuds crafted from premium materials with exceptional sound clarity.",
    fullDescription:
      "SOLARA Orbit Earbuds deliver an uncompromising audio experience in a remarkably compact form. Meticulously crafted from premium materials including ceramic and gold accents, these exceptional earbuds feature our proprietary acoustic architecture that reproduces sound with extraordinary detail and spatial accuracy, creating an immersive listening experience wherever you go.",
    price: "$599",
    priceValue: 599,
    category: "audio",
    image: "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?q=80&w=2070&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?q=80&w=2070&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?q=80&w=2079&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1631176093617-e1b9e93b9e1e?q=80&w=2070&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1598331668826-20cecc596b86?q=80&w=2069&auto=format&fit=crop",
    ],
    new: false,
    rating: 4,
    reviewCount: 103,
    features: [
      "Ceramic and 24K gold-accented construction",
      "Custom-designed 10mm beryllium drivers",
      "Active noise cancellation with transparency mode",
      "Spatial audio with dynamic head tracking",
      "8-hour battery life with luxury charging case",
      "Personalized sound profiles with hearing optimization",
    ],
    colors: [
      { name: "Pearl White", value: "#F5F5F5" },
      { name: "Onyx Black", value: "#0A0A0A" },
      { name: "Rose Gold", value: "#B76E79" },
    ],
    specifications: [
      { name: "Driver", value: "10mm Beryllium dynamic" },
      { name: "Frequency Response", value: "5Hz - 40kHz" },
      { name: "Noise Cancellation", value: "Hybrid ANC with 3 modes" },
      { name: "Battery Life", value: "8 hours (ANC off), 6 hours (ANC on)" },
      { name: "Case Battery", value: "Additional 24 hours" },
      { name: "Charging", value: "USB-C and Qi wireless" },
      { name: "Water Resistance", value: "IPX5" },
      { name: "Connectivity", value: "Bluetooth 5.3, Multipoint" },
      { name: "Codecs", value: "LDAC, aptX Adaptive, AAC, SBC" },
      { name: "Microphones", value: "6 beamforming mics with AI noise reduction" },
      { name: "Controls", value: "Touch and motion sensors" },
      { name: "Weight", value: "5.4g per earbud, 45g case" },
    ],
  },
  {
    id: 9,
    name: "SOLARA Infinity Smart Ring",
    description: "Elegant smart ring that monitors health metrics and connects to your devices.",
    fullDescription:
      "The SOLARA Infinity Smart Ring represents the perfect fusion of jewelry and technology. Crafted from premium materials including titanium and ceramic, this elegant ring seamlessly tracks your health and wellness while providing subtle notifications and controls for your digital life. Wear it as a statement piece that enhances your style while quietly optimizing your wellbeing.",
    price: "$799",
    priceValue: 799,
    category: "wearables",
    image: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=2070&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=2070&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?q=80&w=2070&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=2187&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1573408301185-9146fe634ad0?q=80&w=2069&auto=format&fit=crop",
    ],
    new: true,
    rating: 4,
    reviewCount: 42,
    features: [
      "Crafted from grade 5 titanium with ceramic inner shell",
      "Comprehensive health tracking including heart rate and sleep analysis",
      "Gesture controls for connected devices",
      "Subtle haptic notifications",
      "7-day battery life with wireless charging",
      "Water resistant to 100 meters",
    ],
    colors: [
      { name: "Titanium Gray", value: "#8C8C8C" },
      { name: "Ceramic Black", value: "#0A0A0A" },
      { name: "Gold", value: "#D4AF37" },
    ],
    specifications: [
      { name: "Material", value: "Grade 5 Titanium, Ceramic" },
      { name: "Sensors", value: "Heart rate, SpO2, Temperature, Accelerometer" },
      { name: "Battery Life", value: "Up to 7 days" },
      { name: "Charging", value: "Wireless charging dock" },
      { name: "Connectivity", value: "Bluetooth 5.3 LE" },
      { name: "Water Resistance", value: "10 ATM (100m)" },
      { name: "Sizes", value: "US 6-13 (whole and half sizes)" },
      { name: "Width", value: "7.5mm" },
      { name: "Thickness", value: "2.5mm" },
      { name: "Weight", value: "4-6g (size dependent)" },
      { name: "Compatibility", value: "iOS 14+, Android 10+" },
      { name: "App", value: "SOLARA Connect (iOS/Android)" },
    ],
  },
]

// Function to get related products
export function getRelatedProducts(category: string, currentProductId: number, limit = 3) {
  // First get products in the same category
  const sameCategory = products.filter((p) => p.category === category && p.id !== currentProductId)

  // If we have enough products in the same category, return them
  if (sameCategory.length >= limit) {
    return sameCategory.slice(0, limit)
  }

  // Otherwise, add products from other categories to reach the limit
  const otherProducts = products.filter((p) => p.category !== category && p.id !== currentProductId)

  return [...sameCategory, ...otherProducts].slice(0, limit)
}
